### ISSUE TITLE
About python-fbxsdk modules

### ISSUE THREAD

**Issue by Joong-Sunny** [softcat477/SMPL-to-FBX#1]
Trying to convert .pkl files from AIST++, I`m troubling with some classes

I guess it is from imported packages from FbxCommon.

2020 version would be fine? and I wonder if I can know how did you installed fbxsdk
Autodesk provides diffrent ways
1) Install fbxsdk and wrapp with python bindings
2) install python-fbxsdk
which one did you get?
I think it would help my problem

**Comment by softcat477** [comment]
Hello,
I use python-fbx sdk. Here's the step to install it:
1. Install FBX Python SDK from here: https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-0. I use the 2020.0.1 version.
2. Follow https://download.autodesk.com/us/fbx/20112/fbx_sdk_help/index.html?url=WS1a9193826455f5ff453265c9125faa23bbb5fe8.htm,topicNumber=d0e8312. Basically, you have to move `<yourFBXSDKpath>\lib\<Pythonxxxxxx>\` into the right directory.
3. Change the `'ascii'` in `FbxCommon::SaveScene` to `'binary'`. The fbx-ascii file format loads and saves slower than the binary format.
4. The python-fbx sdk might only work with python 3.7. If you keep facing problems, try to use python-3.7.

**Comment by Joong-Sunny** [comment]
OMG, I succeed!!!

For posterity,
I did follow the same instruction as they explained and double checked,
but trying to import fbx.so, terminal says 'no module named fbxsip'

So, I trying to import fbxsip.so by command
import fbx.fbxsip
and then trying to import fbx.so, but again, it says 'no module named fbxsip'

I solved this problem by pulled every items out side of the packages
I don`t know why python-fbxsdk is not working with packages but working with independent modules

(before solved the problem)

<(conda)site-pakcages>
  | --numpy
  | --tqdm
  | --fbx
    | --fbx.so
    | --FbxComm.py
    | --fbxsip.so


(after solved the problem)

<(conda)site-pakcages>
  | --numpy
  | --tqdm
  | --fbx.so
  | --FbxComm.py
  | --fbxsip.so

**Comment by innopeak-zhangsihao-yang** [comment]
hi, are you use windows platform? it seems that I can not download the same python files anymore. if possible do you mind share the .so .py files here? thanks, it seems that they make changes to the exe file in their website.

**Comment by Joong-Sunny** [comment]
@innopeak-zhangsihao-yang  I did it with Widows. Recently, I moved AI to FE engineer. I'll looking for the computer I used in a week(may take some time..) :)
