### ISSUE TITLE
smpl trans value seems not work

### ISSUE THREAD

**Issue by tianyu06030020** [softcat477/SMPL-to-FBX#11]
when import the fbx to blender,  There's  no translation frame to frame, the trans value is below:
![image](https://user-images.githubusercontent.com/9124519/186880669-6fedab79-0c7d-4f5f-a6c6-c1af2eac34a4.png)

in blender, It shows like this:

![image](https://user-images.githubusercontent.com/9124519/186880886-d33439de-6e32-4520-8c17-a381186224d7.png)

**Comment by StayYouth1993** [comment]
me too！

**Comment by XH-B** [comment]
Hey guys, I also encountered this problem, how did you solve it?

**Comment by DESEOUMAIGA** [comment]
Anyone got the answer?

**Comment by OB1kanOB** [comment]
Hey, I got the same issue. The model joints move in place but there is no translation. Did anyone figure out a solution.
Appreciate your time and input.
Thanks!

**Comment by softcat477** [comment]
close as lacking details to replicate.
