### ISSUE TITLE
How do I use my custom pose data with this?

### ISSUE THREAD

**Issue by aneeshbhattacharya** [softcat477/SMPL-to-FBX#13]
Hi! I have my custom pose data where I have the joint positions of each frame.
I have 18 keypoints and each has X,Y,Z coordinates representing their positions with respect to the centre 0,0,0.
I am hoping to use the Mixamo models to animate my poses.
Could you please shed some light as to how I can use this work to achieve that?
To make it easier:
I have 100 frames
Each frame has 18x3 data, 18 is keypoints and 3 is X,Y,Z axis position relative to 0,0,0

**Comment by softcat477** [comment]
Hey since this package only supports the axis-angle representation, I would say try something like SMPL to predict axis-angle representation from x/y/z position. or you can take a look at how aist++ processed their 3-d dance motion to get the axis-angle representation.

**Comment by softcat477** [comment]
perhaps this would help: https://github.com/GuyTevet/motion-diffusion-model/tree/main/visualize/joints2smpl

**Comment by aneeshbhattacharya** [comment]
Thank you for your response. I will look into it and let you know!
