### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by mmdrahmani** [softcat477/SMPL-to-FBX#15]
Hi
I followed the instructions and installed fbx sdk on my macbook and then the smpl-to-fbx requirements in a new conda environment. Then while running the Python Convert.py I got this error (without more info):

['gBR', 'gPO', 'gLO', 'gMH', 'gLH', 'gHO', 'gWA', 'gKR', 'gJS', 'gJB']
['sBM', 'sFM']
['0', '1', '2', '3', '4', '5']
Segmentation fault: 11

Do you have any ideas why I am getting this error? My guess the FBX sdk configuration was not done properly, although I followed the instructions provided.
Thanks

**Comment by philmaas** [comment]
potentially related. I get a similar error when defining the --output-base path to be anything other than "./" 
```
['gBR', 'gPO', 'gLO', 'gMH', 'gLH', 'gHO', 'gWA', 'gKR', 'gJS', 'gJB']
['sBM', 'sFM']
['0', '1', '2', '3', '4', '5']
  0%|          | 0/2 [00:00<?, ?it/s]Segmentation fault
```

Try using --output_base ./
`python3 Convert.py --input_pkl_base ./Pkls/ --fbx_source_path ./fbx/SMPL_m_unityDoubleBlends_lbs_10_scale5_207_v1.0.0.fbx --output_base ./
`

**Comment by softcat477** [comment]
This repo use `FXB Python SDK 2020.0.1`. You may encounter segmentation fault if not using the same FBX SDK version. See #25 for details.
