### ISSUE TITLE
Which version did you use?

### ISSUE THREAD

**Issue by StayYouth1993** [softcat477/SMPL-to-FBX#17]
I use the latest fbx version, and rebuild myself. Trans value not work! I think the reason might be diff version of fbx sdk, can you provide your version?

**Comment by CodedRedGIT** [comment]
I'm using the latest version of the sdk (FBX SDK 2020.3.2 Python) with Python 3.7 and it works great.

**Comment by HitLyn** [comment]
I have the same problem, have you already solved it?

**Comment by softcat477** [comment]
FBX Python SDK version 2020.0.1
