### ISSUE TITLE
PythonFBX SDK version

### ISSUE THREAD

**Issue by tommyshelby4** [softcat477/SMPL-to-FBX#20]
I cannot find the PythonFBX SDK version for Python 3. Does anybody have a clue on where I can find it? I can only find the version for Python 2.7

**Comment by Minsoo2022** [comment]
Same problem.... I downloaded fbx202001_fbxpythonsdk_linux.tar.gz, but there is only python2.7 version in lib folder

**Comment by fangyuansama** [comment]
[https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-3](url) Here is the PythonFBX SDK for Python 3.7.
