### ISSUE TITLE
About 3D character mixamo you show in the video 

### ISSUE THREAD

**Issue by wzyabcas** [softcat477/SMPL-to-FBX#4]
I'm a rookie in blender and 3D visualization. I found it amazing that the mixamo character is dancing in the video you show on github,and I'm curious that how you made that.Did you make it in blender or just by the code you provide? If in blender,can you give a detailed instruction on how to do that ,since I've tried it in blender and failed.

**Comment by softcat477** [comment]
Hello,
I use Unity to retarget the fbx file(by my code) to a maximo character. Here's some tutorial video: [https://www.youtube.com/watch?v=BEZHVYk6Fa4](https://www.youtube.com/watch?v=BEZHVYk6Fa4)

**Comment by lvZic** [comment]
> 



> Hello, I use Unity to retarget the fbx file(by my code) to a maximo character. Here's some tutorial video: https://www.youtube.com/watch?v=BEZHVYk6Fa4

hi, i wonder if retarget is the only way to use cvt SMPL to a maximo character.  Is there any any to directly get a maximo character fbx by Convert.py?
