### ISSUE TITLE
NameError: name 'FbxAnimCurve' is not defined

### ISSUE THREAD

**Issue by ZariAdas** [softcat477/SMPL-to-FBX#5]
Hi,

I have installed the FBXSDK and copied the files to my PC python path. But when I want to convert .pkl files to .fbx I see this error.
I tried python 2.7, 3.2, 3.7 and 3.9

**Comment by softcat477** [comment]
hello,
which fbx version are you using?
About install guidelines, you can refer to this: https://github.com/softcat477/SMPL-to-FBX/issues/1#issuecomment-995204534

**Comment by JiananZhao0224** [comment]
> 

hi, I have the same error, have you already solved this problem? thx

**Comment by mlknz** [comment]
for me that error meant that FBX SDK wasn't visible in my env.
I installed it to global env and script worked, but to get it working in PyCharm I had to copy fbx*-related files from global site-packages to venv site-packages.
