### ISSUE TITLE
Save FBX as Binary format

### ISSUE THREAD

**Issue by zhangsanfeng86** [softcat477/SMPL-to-FBX#6]
Hi @softcat477 
Thanks for release code.
How to save FBX as Binary format?

**Comment by softcat477** [comment]
hey,
as far as I remembered, `ascii` is hard-coded in `fbxsdk`. Maybe you can try go to their code and search for `ascii` and change it to `binary`

**Comment by zhangsanfeng86** [comment]
thank you

**Comment by spthermo** [comment]
> Could you mention where exactly we should edit the fbxsdk to get a binary version of the FBX file?

In case you never found a solution, you need to change an if statement in the FbxCommon.py script. Just change `ascii` to `binary` and re-run the fbx exporter. Now you can import the new fbx file to blender.
